version: 2.1

jobs:
  build:
    docker:
      - image: ryangraham/cfg:0.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Run tests
          command: ./build/cfg_test
